#!/bin/bash

# Social Lobby Deployment Script
# This script helps automate the deployment process

echo "🚀 Social Lobby Deployment Helper"
echo "=================================="
echo ""

# Check if MongoDB Atlas URL is set
if [ -z "$MONGODB_ATLAS_URI" ]; then
    echo "⚠️  WARNING: MONGODB_ATLAS_URI environment variable not set"
    echo "   Please create a MongoDB Atlas cluster and set the connection string"
    echo ""
fi

echo "📋 Deployment Checklist:"
echo ""
echo "Backend Deployment (Render):"
echo "  1. Go to https://render.com and sign in"
echo "  2. Click 'New +' → 'Web Service'"
echo "  3. Connect your GitHub repository: marciliobbarboza2/Social-Lobby"
echo "  4. Configure:"
echo "     - Name: socialobby-backend"
echo "     - Root Directory: backend"
echo "     - Build Command: npm install"
echo "     - Start Command: node server.js"
echo "  5. Add Environment Variables:"
echo "     - MONGODB_URI=<your-mongodb-atlas-connection-string>"
echo "     - JWT_SECRET=<generate-a-secure-random-string>"
echo "     - PORT=5000"
echo "     - NODE_ENV=production"
echo "  6. Click 'Create Web Service'"
echo "  7. Wait for deployment (~5-10 minutes)"
echo "  8. Copy your backend URL (e.g., https://socialobby-backend.onrender.com)"
echo ""
echo "Frontend Deployment (Vercel):"
echo "  1. Go to https://vercel.com and sign in"
echo "  2. Click 'Add New' → 'Project'"
echo "  3. Import your GitHub repository: marciliobbarboza2/Social-Lobby"
echo "  4. Configure:"
echo "     - Framework Preset: Vite"
echo "     - Root Directory: ./"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "  5. Add Environment Variables:"
echo "     - VITE_API_URL=<your-render-backend-url>"
echo "  6. Click 'Deploy'"
echo "  7. Wait for deployment (~2-5 minutes)"
echo "  8. Copy your frontend URL (e.g., https://socialobby.vercel.app)"
echo ""
echo "Post-Deployment:"
echo "  1. Update backend CORS in backend/server.js to include your Vercel URL"
echo "  2. Redeploy backend on Render"
echo "  3. Test all features:"
echo "     - User registration/login"
echo "     - Create/edit/delete posts"
echo "     - Like/comment functionality"
echo "     - Search/filter"
echo "     - Settings page"
echo ""
echo "✅ All configuration files are ready in your repository!"
echo ""
